CREATE TABLE `b2b_vip_management_grant` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `vip_management_grant_no` varchar(32) NOT NULL COMMENT '会员交易记录no',
  `vip_grade_tp_id` bigint(20) NOT NULL COMMENT '会员等级id',
  `vip_grade_ins_id` bigint(20) DEFAULT '0' COMMENT '会员等级实例id，在支付完成时生成',
  `partner_name` varchar(128) NOT NULL DEFAULT '' COMMENT '公司名',
  `partner_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '公司id',
  `contract_id` varchar(64) DEFAULT NULL COMMENT '协议合同ID',
  `contract_sign_time` datetime DEFAULT NULL COMMENT '合同签约时间',
  `balance_fee` bigint(20) unsigned NOT NULL COMMENT '开通会员余额，单位分',
  `service_fee` bigint(20) NOT NULL COMMENT '开通会员手续费，单位分',
  `vip_total_fee` bigint(20) NOT NULL COMMENT '开通会员总费用，单位分',
  `deduction_fee` bigint(20) NOT NULL COMMENT '余额抵扣费用，单位分',
  `total_pay_fee` bigint(20) NOT NULL COMMENT '所需支付费用，单位分',
  `grant_type` tinyint(2) NOT NULL COMMENT '开通类型，0：开通，1：升级，2：重新购买，3：叠加购买，4：再次购买',
  `fee_code` varchar(45) DEFAULT '' COMMENT '财务账单唯一码',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `status` tinyint(2) DEFAULT '0' COMMENT '开通状态，0：已签署待支付，1：支付完成待激活，2：失效',
  `activate_status` tinyint(2) DEFAULT '0' COMMENT '激活状态状态，0：未激活，1：已激活',
  `manager_id` bigint(20) DEFAULT '0' COMMENT '业务经理id',
  `manager_name` varchar(32) DEFAULT '' COMMENT '业务经理名',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0未删除 1已删除',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '业务经理部门',
  `referrer_name` varchar(16) NOT NULL DEFAULT '' COMMENT '推荐人姓名',
  `referrer_mobile` varchar(16) NOT NULL DEFAULT '' COMMENT '推荐人手机号',
  `referrer_corp` varchar(64) NOT NULL DEFAULT '' COMMENT '推荐人公司',
  `payer_name` varchar(16) NOT NULL DEFAULT '' COMMENT '付款人姓名',
  `payer_mobile` varchar(16) NOT NULL DEFAULT '' COMMENT '付款人手机号',
  `payer_corp` varchar(64) NOT NULL DEFAULT '' COMMENT '付款人公司',
  `purchase_entry` tinyint(4) NOT NULL DEFAULT '1' COMMENT '购买入口1：app 2：小程序',
  
  `refund_operator` varchar(16) NOT NULL DEFAULT '' COMMENT '退费操作人',
  `refund_amount` bigint(20) DEFAULT NULL COMMENT '退费金额单位（分）',
  `refund_time` datetime DEFAULT NULL COMMENT '退费时间',
  `refund_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '退费备注',
  `associate_operator` varchar(16) NOT NULL DEFAULT '' COMMENT '关联操作人',
  `associate_time` datetime DEFAULT NULL COMMENT '关联时间',
  `associate_partner_name` varchar(16) NOT NULL COMMENT '关联操作人',
  PRIMARY KEY (`id`),
  KEY `idx_vip_grant_no` (`vip_management_grant_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1201 DEFAULT CHARSET=utf8mb4 COMMENT='会员开通记录表';